<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;


class GithubController extends Controller
{
    /*
    | api() generated by Composer
    | composer require graham-campbell/github:^10.0 guzzlehttp/guzzle:^7.0.1 http-interop/http-factory-guzzle:^1.0
    */

    public function finder()
    {
        $repo = Input::get('repo');

        try {
            if ($repo) {
                $result = $this->client->api('repo')->contents()->show($this->username, $repo);
            }

            return View::make('search', ['repo' => $repo, 'items' => $result]);

        } catch (\RuntimeException $e) {
            $this->handleAPIException($e);
        }
    }
}
